theme: jekyll-theme-minimal
title: CompuNet Azure Templates
description: Azure ARM Templates used for various deployment types.
logo: images/cnet.png
# _portfolio
  - scope:
      path: "pfchangs"
      type: pages
    values:
      logo: endor.png
